package myfirstapplication;

import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Kanishk Mittal (ID - 2156564)
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStatusPanel = new javax.swing.JPanel();
        jStatusMessageLabel = new javax.swing.JLabel();
        jStatusAnimationLabel = new javax.swing.JLabel();
        jProgressCompletionBar = new javax.swing.JProgressBar();
        jMainPanel = new javax.swing.JPanel();
        jMainTabbedPane = new javax.swing.JTabbedPane();
        jLoginPanel = new javax.swing.JPanel();
        jNameLabel = new javax.swing.JLabel();
        jNameTextField = new javax.swing.JTextField();
        jLoginButton = new javax.swing.JButton();
        jCalculatorPanel = new javax.swing.JPanel();
        jInputLabel1 = new javax.swing.JLabel();
        jInputTextField1 = new javax.swing.JTextField();
        InputLabel2 = new javax.swing.JLabel();
        jInputTextField2 = new javax.swing.JTextField();
        jOutputLabel3 = new javax.swing.JLabel();
        jOutputTextField = new javax.swing.JTextField();
        jAddButton = new javax.swing.JButton();
        jSubstractButton = new javax.swing.JButton();
        jMultiplyButton = new javax.swing.JButton();
        jDivideButton = new javax.swing.JButton();
        jPowerButton = new javax.swing.JButton();
        jVolumeOfSphereButton = new javax.swing.JButton();
        jVolumeOfCylinderButton = new javax.swing.JButton();
        jSquareBasedPyramidVolButton = new javax.swing.JButton();
        jLogOutButton = new javax.swing.JButton();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jStatusPanel.setBackground(new java.awt.Color(204, 204, 204));
        jStatusPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N

        jStatusMessageLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jStatusMessageLabel.setText("My First Application is Running");

        jProgressCompletionBar.setBackground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jStatusPanelLayout = new javax.swing.GroupLayout(jStatusPanel);
        jStatusPanel.setLayout(jStatusPanelLayout);
        jStatusPanelLayout.setHorizontalGroup(
            jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jStatusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressCompletionBar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jStatusPanelLayout.createSequentialGroup()
                    .addGap(0, 359, Short.MAX_VALUE)
                    .addComponent(jStatusAnimationLabel)
                    .addGap(0, 359, Short.MAX_VALUE)))
        );
        jStatusPanelLayout.setVerticalGroup(
            jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressCompletionBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jStatusPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jStatusMessageLabel)))
                .addGap(92, 92, 92))
            .addGroup(jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jStatusPanelLayout.createSequentialGroup()
                    .addGap(0, 56, Short.MAX_VALUE)
                    .addComponent(jStatusAnimationLabel)
                    .addGap(0, 56, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        jMainTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMainTabbedPaneMousePressed(evt);
            }
        });

        jLoginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLoginPanel.setRequestFocusEnabled(false);

        jNameLabel.setText("What is you Name ?");

        jLoginButton.setText("Login");
        jLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLoginButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNameLabel)
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addComponent(jNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLoginButton)))
                .addContainerGap(477, Short.MAX_VALUE))
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLoginButton))
                .addContainerGap(402, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Login", jLoginPanel);

        jInputLabel1.setText("Input 1");

        jInputTextField1.setText("0.0");

        InputLabel2.setText("Input 2");

        jInputTextField2.setText("0.0");

        jOutputLabel3.setText("Output");

        jOutputTextField.setText("0.0");

        jAddButton.setText("+");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSumButtonActionPerformed(evt);
            }
        });

        jSubstractButton.setText("-");
        jSubstractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubstractButtonActionPerformed(evt);
            }
        });

        jMultiplyButton.setText("*");
        jMultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMultiplyButtonActionPerformed(evt);
            }
        });

        jDivideButton.setText("/");
        jDivideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDivideButtonActionPerformed(evt);
            }
        });

        jPowerButton.setText("pow");
        jPowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPowerButtonActionPerformed(evt);
            }
        });

        jVolumeOfSphereButton.setText("Volume Of Sphere");
        jVolumeOfSphereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolumeOfSphereButtonActionPerformed(evt);
            }
        });

        jVolumeOfCylinderButton.setText("Volume Of Cylinder");
        jVolumeOfCylinderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCylinderVolumeAction(evt);
            }
        });

        jSquareBasedPyramidVolButton.setText("SquareBasedPyramid Volume");
        jSquareBasedPyramidVolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSquareBasedPyramidVolButtonActionPerformed(evt);
            }
        });

        jLogOutButton.setText("Log Out");
        jLogOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogOutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jCalculatorPanelLayout = new javax.swing.GroupLayout(jCalculatorPanel);
        jCalculatorPanel.setLayout(jCalculatorPanelLayout);
        jCalculatorPanelLayout.setHorizontalGroup(
            jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                .addComponent(jOutputLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jInputLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jInputTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOutputTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCalculatorPanelLayout.createSequentialGroup()
                        .addComponent(jAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSubstractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jMultiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jVolumeOfCylinderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jVolumeOfSphereButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSquareBasedPyramidVolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLogOutButton)
                .addGap(78, 78, 78))
        );
        jCalculatorPanelLayout.setVerticalGroup(
            jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputLabel1)
                    .addComponent(jInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputLabel2)
                    .addComponent(jInputTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOutputLabel3)
                    .addComponent(jOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddButton)
                    .addComponent(jSubstractButton)
                    .addComponent(jMultiplyButton)
                    .addComponent(jDivideButton))
                .addGap(18, 18, 18)
                .addComponent(jPowerButton)
                .addGap(12, 12, 12)
                .addComponent(jVolumeOfCylinderButton)
                .addGap(18, 18, 18)
                .addComponent(jVolumeOfSphereButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSquareBasedPyramidVolButton)
                    .addComponent(jLogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Calculator", jCalculatorPanel);

        jMenu3.setText("File");
        jMenuBarMain.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBarMain.add(jMenu4);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jStatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMainTabbedPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jMainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 // In Above portion lies the Machine Generated Code.
    

    // Code for executing the sum of two values.
    private void jSumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSumButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.valueOf(jInputTextField1.getText());
        double input2 = Double.valueOf(jInputTextField2.getText());
        
        double output = input1+ input2;
        
         jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jSumButtonActionPerformed

    // Code for executing substraction between two numbers 
    private void jSubstractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubstractButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.valueOf(jInputTextField1.getText());
        double input2 = Double.valueOf(jInputTextField2.getText());
        
        double output = input1 - input2;
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jSubstractButtonActionPerformed

    // Code for executing Multiplication between two numbers 
    private void jMultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMultiplyButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.valueOf(jInputTextField1.getText());
        double input2 = Double.valueOf(jInputTextField2.getText());
        
        double output = input1 * input2;
        
        
       jOutputTextField.setText(String.valueOf(output));;
    }//GEN-LAST:event_jMultiplyButtonActionPerformed

    // A separate method has been created for Data Validation for Dividing two numbers
    private boolean jDivisionDataValidation(double input1, double input2){
        
        boolean dataInvalid = false;
        if (input1 ==0 || input2 == 0 ){
            dataInvalid = true;  
        }
        return dataInvalid;
        
    }
    
    // Code for executing Division between two numbers
    private void jDivideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDivideButtonActionPerformed
       
        double input1 = Double.valueOf(jInputTextField1.getText());
        double input2 = Double.valueOf(jInputTextField2.getText());
        
        // As one can observe an external function to validate the data provided by the user.
        if (jDivisionDataValidation(input1, input2) ) { 
            jOutputTextField.setText("Division by Zero not possible");
        }
        
        else{
            double output = input1 / input2;
        
            jOutputTextField.setText(String.format("%.4f",output)); 
            // Here we have rounded up the output by using the string.format to four decimal places.
        }
        
        
    }//GEN-LAST:event_jDivideButtonActionPerformed

    // We declared a separate power method for the implementation of different functions as this method will be used
    // everywhere else.
    private double power(double input1, double input2){
        double result = 1; 
        for (int i = 0; i < input2; i++) {
            result *= input1; 
        }
        return result; 
    }
    
    // Code to execute the power function
    private void jPowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPowerButtonActionPerformed
       
        double input1 = Double.valueOf(jInputTextField1.getText());
        double input2 = Double.valueOf(jInputTextField2.getText());
        
        
        double output = power(input1,  input2);
        
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jPowerButtonActionPerformed

    private void jCylinderVolumeAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCylinderVolumeAction
       
        double input1 = Double.valueOf(jInputTextField1.getText());
        double input2 = Double.valueOf(jInputTextField2.getText());
        
        
        double output = ((22.0/7.0) * power(input1,2) * input2 );
        
        // We have the rounded up the floating points upto 4 decimal places to improve presentation of the calculator.
        jOutputTextField.setText(String.format("%.4f",output));
        
    }//GEN-LAST:event_jCylinderVolumeAction

    private void jVolumeOfSphereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolumeOfSphereButtonActionPerformed
        
        double input1 = Double.valueOf(jInputTextField1.getText());
        double input2 = Double.valueOf(jInputTextField2.getText());
        
        
        double output = ((4.0/3.0) * (22.0/7.0) * power(input1,3) );
        
        // We have the rounded up the floating points upto 4 decimal places to improve presentation of the calculator.
        jOutputTextField.setText(String.format("%.1f",output));
    }//GEN-LAST:event_jVolumeOfSphereButtonActionPerformed

    private void jSquareBasedPyramidVolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSquareBasedPyramidVolButtonActionPerformed
        
        double input1 = Double.valueOf(jInputTextField1.getText());
        double input2 = Double.valueOf(jInputTextField2.getText());
        
        
        double output = (power(input1,2)* (input2/3) );
        
        // We have the rounded up the floating points upto 4 decimal places to improve presentation of the calculator.
        jOutputTextField.setText(String.format("%.4f",output));
    }//GEN-LAST:event_jSquareBasedPyramidVolButtonActionPerformed

    
    
    // This is a separate method to validate the name field on the main login page so that
    // any user is not allowed to login if they leave the name field empty, this method can be used
    // on any other text field validation as well.
    private boolean jLoginValidation(String text){
        text = jNameTextField.getText();
        boolean nameFieldEmpty = false;
        if ((text.equals(""))){
            nameFieldEmpty = true;
          
        }
        return nameFieldEmpty;
    }
    
    private void jLoginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButtonMousePressed
        // TODO add your handling code here:
        
        if (jLoginValidation(jNameTextField.getText())){
          jStatusMessageLabel.setText("Please Enter a name to Login..."); 
          jMainTabbedPane.setSelectedIndex(0);
          jStatusMessageLabel.setForeground(Color.red);
        }
        
        else{
        jMainTabbedPane.setSelectedIndex(1);
        jStatusMessageLabel.setText(jNameTextField.getText()+ " is logged in...");
        jStatusMessageLabel.setForeground(new java.awt.Color(0, 100, 0));
        
        }
    }//GEN-LAST:event_jLoginButtonMousePressed

    // This is an event handler that prevents the user from jumping to the calculator page without providing a name
    // One can also not the change in color of error messages once an error pops up or in case there is a successful login.
    private void jMainTabbedPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMainTabbedPaneMousePressed
        // TODO add your handling code here:
        if (jLoginValidation(jNameTextField.getText())){
        jMainTabbedPane.setSelectedIndex(0);
        jStatusMessageLabel.setText("Please Enter a name to Login..."); 
        jStatusMessageLabel.setForeground(Color.red);
        }
        else{
        jStatusMessageLabel.setText(jNameTextField.getText()+ " is logged in..."); 
        jStatusMessageLabel.setForeground(new java.awt.Color(0, 100, 0));
        }
    }//GEN-LAST:event_jMainTabbedPaneMousePressed

    private void jLogOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogOutButtonMouseClicked
        // TODO add your handling code here:
        jStatusMessageLabel.setText("Please Enter a name to Login...");
        jStatusMessageLabel.setForeground(new java.awt.Color(0, 0, 0));
        jMainTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_jLogOutButtonMouseClicked

    // No external Math libraries have been used thought out this program.
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InputLabel2;
    private javax.swing.JButton jAddButton;
    private javax.swing.JPanel jCalculatorPanel;
    private javax.swing.JButton jDivideButton;
    private javax.swing.JLabel jInputLabel1;
    private javax.swing.JTextField jInputTextField1;
    private javax.swing.JTextField jInputTextField2;
    private javax.swing.JButton jLogOutButton;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JTabbedPane jMainTabbedPane;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JButton jMultiplyButton;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JTextField jNameTextField;
    private javax.swing.JLabel jOutputLabel3;
    private javax.swing.JTextField jOutputTextField;
    private javax.swing.JButton jPowerButton;
    private javax.swing.JProgressBar jProgressCompletionBar;
    private javax.swing.JButton jSquareBasedPyramidVolButton;
    private javax.swing.JLabel jStatusAnimationLabel;
    private javax.swing.JLabel jStatusMessageLabel;
    private javax.swing.JPanel jStatusPanel;
    private javax.swing.JButton jSubstractButton;
    private javax.swing.JButton jVolumeOfCylinderButton;
    private javax.swing.JButton jVolumeOfSphereButton;
    // End of variables declaration//GEN-END:variables
}
